version: "3.3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=myPass123
