spring:
  profiles:
    active: local
---
########################################################################################################################
# Local
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:file:~/rabobank/scma_sfc_local/database;MODE=ORACLE
  h2:
    console:
      enabled: true
      path: /h2-console
