spring:
  profiles:
    active: local
---
########################################################################################################################
# Local
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:file:~/covestro_local/database;MODE=ORACLE
  h2:
    console:
      enabled: true
      path: /h2-console

covestro:
  products:
    jwt:
      signingKey: LOCAL_KEY
      expirationMillis: 604800
      headerName: AuthorizationAlt
  requester: ADMIN